services:
  app:
    container_name: dashboard-sql-report
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: $API_URL
    environment:
        API_URL: $API_URL
    ports:
      - "4203:4000"
