services:
  app:
    container_name: dota-shuffle-angular
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: $API_URL
        WS_URL: $WS_URL
    environment:
        API_URL: $API_URL
        WS_URL: $WS_URL
    ports:
      - "4203:4000"
